### ISSUE TITLE
table pets has no column named weight

### ISSUE THREAD

**Issue by shaurya96** [udacity/ud845-Pets#14]
Error inserting name=Toto gender=1 weight=7 breed=Terrier
                                                                        android.database.sqlite.SQLiteException: table pets has no column named weight (code 1): , while compiling: INSERT INTO pets(name,gender,weight,breed) VALUES (?,?,?,?)

**Comment by vcctu85** [comment]
Hi @shaurya96 , double check your syntax and the order of your arguments. Or if you can specify exactly where in the code you're getting this error, I'd be happy to look at it for you.

**Comment by ChandoraAnkit** [comment]
clear your app  data  and cache and try again..

**Comment by AlShaymaa1** [comment]
uninstall the app and install it again

**Comment by akwa-peter** [comment]
Am having same issue, have same issue and have cleared my data, uninstalled and installed back, but stilll having same issue

**Comment by M-Kalita** [comment]
@akwa-peter  and @shaurya96 

UNINSTALL THE APP AND TRY AGAIN! SAME ERROR SHOWED IN MINE APP TOO BUT AFTER REINSTALLING IT,it worked fine.

**Comment by jamin-hu** [comment]
Uninstalling the app and reinstalling it solved the same issue for me!

**Comment by essopsp** [comment]
Solution

`String query = "CREATE TABLE "+TABLE_RejectList+"("+
        COLUMN_NUMBER+"TEXT PRIMARY KEY);";`

You forgot the space between **COLUMN_NUMBER** and "**TEXT**", it should be:

`String query = "CREATE TABLE "+TABLE_RejectList+"("+
        COLUMN_NUMBER+" TEXT PRIMARY KEY);";`

**Comment by RubinTry** [comment]
@akwa-peter This is a amazing situation！It's may a bug on Android

**Comment by KurModi** [comment]
@essopsp You are right

**Comment by surajmaity1** [comment]
> Solution
> 
> `String query = "CREATE TABLE "+TABLE_RejectList+"("+ COLUMN_NUMBER+"TEXT PRIMARY KEY);";`
> 
> You forgot the space between **COLUMN_NUMBER** and "**TEXT**", it should be:
> 
> `String query = "CREATE TABLE "+TABLE_RejectList+"("+ COLUMN_NUMBER+" TEXT PRIMARY KEY);";`

It worked for me..
Thanks a lot

**Comment by AsogwaTech** [comment]
Clearing the cache and deleting the app data storage. Then uninstalled the app, it works!
