### ISSUE TITLE
starting-point code doesn't match the code described in the video

### ISSUE THREAD

**Issue by Mahmoud-Gad** [udacity/ud845-Pets#18]
in lesson 2 in the database course, in the second tab "importing existing project", when we view the answer to the quiz, the view describes a different starting code.

the starting code shouldn't contain the package file named "data" and the contents of the java codes are different as well, this is probably an advanced version of the code. how can i get the right one?

**Comment by ridhwandaud** [comment]
I also happen to got the same problem . This is because the default branch is lesson-two branch. To fixed this . Go to terminal and **_git checkout starting-point_** . Hope this helps others.
