### ISSUE TITLE
mGender is never defined properly by reading selected spinner value in EditorActivity.

### ISSUE THREAD

**Issue by runnerlt** [udacity/ud845-Pets#22]
We have `private int mGender = 0;` only. 
Need to add something like `mGender = (int) mGenderSpinner.getSelectedItemId();`

**Comment by getsadzeg** [comment]
Why? We assign values with constants(`GENDER_MALE`, `GENDER_FEMALE`, `GENDER_UNKNOWN`) depending on what user selects, in overriden `OnItemSelected` method. It works properly, as it should.
