### ISSUE TITLE
How to manage SQLite database , query method with Particular row id

### ISSUE THREAD

**Issue by Dev-Aslan** [udacity/ud845-Pets#29]
sUrimatcher.match(uri); is returning -1.
It should return 101.
Can you help me with that?

PetProvider.java-:

package com.example.android.pets.data;

import android.content.ContentProvider;
import android.content.ContentUris;
import android.content.ContentValues;
import android.content.UriMatcher;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.net.Uri;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.text.Selection;
import android.util.Log;
import android.widget.Toast;

public class PetsProvider extends ContentProvider {
    private PetsDbHelper mDbHelper;
    private static final UriMatcher sUriMatcher = new UriMatcher(UriMatcher.NO_MATCH);
    private static final int PETS = 100;
    private static final int PET_ID = 101;

    static {
        sUriMatcher.addURI(PetsContract.CONTENT_AUTHORITY, PetsContract.PATH_PETS, PETS);
    }

    @Override
    public boolean onCreate() {
        mDbHelper = new PetsDbHelper(getContext());
        return false;
    }

    @Nullable
    @Override
    public Cursor query(@NonNull Uri uri, @Nullable String[] projection, @Nullable String selection, @Nullable String[] selectionArgs, @Nullable String sortOrder) {
        SQLiteDatabase database = mDbHelper.getReadableDatabase();

        Cursor cursor;
        Log.v(String.valueOf(this),"uri="+uri);
        int match = sUriMatcher.match(uri);

        switch (match) {
            case PETS:
                cursor = database.query(PetsContract.PetsEntry.TABLE_NAME, projection, selection, selectionArgs, null, null, null);
                break;
            case PET_ID:
                selection = PetsContract.PetsEntry._ID + "=?";
                selectionArgs = new String[]{String.valueOf(ContentUris.parseId(uri))};
                cursor = database.query(PetsContract.PetsEntry.TABLE_NAME, projection, selection, selectionArgs, null, null, null);
                break;
                default:
                throw new IllegalArgumentException("unknown Uri " + uri);
        }
        // Set the notification URI on the Cursor
        // So we know that content URI the Cursor was created for
        // If the data at this URI changes ,then we know we need to update the Cursor.
        cursor.setNotificationUri(getContext().getContentResolver(),uri);
        return cursor;
    }

    @Nullable
    @Override
    public String getType(@NonNull Uri uri) {
        int match = sUriMatcher.match(uri);
        switch (match) {
            case PETS:
                return PetsContract.PetsEntry.CONTENT_LIST_TYPE;
            case PET_ID:
                return PetsContract.PetsEntry.CONTENT_ITEM_TYPE;
            default:
                throw new IllegalArgumentException("unknown URI " + uri);
        }

    }

    @Nullable
    @Override
    public Uri insert(@NonNull Uri uri, @Nullable ContentValues values) {

        int match = sUriMatcher.match(uri);
        switch (match) {
            case PETS:
                return insertPets(uri, values);
            default:
                throw new IllegalArgumentException("insertion not possible " + uri);
        }
    }

    private Uri insertPets(Uri uri, ContentValues values) {
        String name = values.getAsString(PetsContract.PetsEntry.COLUMN_PET_NAME);
        if (name == null) {
            throw new IllegalArgumentException("Name of the pet can't be null");
        }
        int weight = values.getAsInteger(PetsContract.PetsEntry.COLUMN_PET_WEIGHT);
        if (weight < 0) {
            throw new IllegalArgumentException("Weight can't be negative");
        }
        SQLiteDatabase database = mDbHelper.getWritableDatabase();
        long row = database.insert(PetsContract.PetsEntry.TABLE_NAME, null, values);
        if (row == -1) {//Toast.makeText(getContext(),"Pet Saved",Toast.LENGTH_SHORT).show();
            Log.e(String.valueOf(this), "Failed to insert " + uri);
        }

        //Notify all Listeners that the data has changed for the pet content URI
        getContext().getContentResolver().notifyChange(uri,null);
        return ContentUris.withAppendedId(uri, row);
    }

    @Override
    public int delete(@NonNull Uri uri, @Nullable String selection, @Nullable String[] selectionArgs) {
        SQLiteDatabase database = mDbHelper.getWritableDatabase();

        final int match = sUriMatcher.match(uri);
        switch (match) {
            case PETS:
                // Delete all rows that match the selection and selection args
                return database.delete(PetsContract.PetsEntry.TABLE_NAME, selection, selectionArgs);
            case PET_ID:
                // Delete a single row given by the ID in the URI
                selection = PetsContract.PetsEntry._ID + "=?";
                selectionArgs = new String[]{String.valueOf(ContentUris.parseId(uri))};
                int rowsDeleted = database.delete(PetsContract.PetsEntry.TABLE_NAME, selection, selectionArgs);
                if(rowsDeleted!=0)
                    getContext().getContentResolver().notifyChange(uri,null);
                return rowsDeleted;
                default:
                throw new IllegalArgumentException("Deletion is not supported for " + uri);
        }

    }

    @Override
    public int update(@NonNull Uri uri, @Nullable ContentValues values, @Nullable String selection, @Nullable String[] selectionArgs) {
        final int match = sUriMatcher.match(uri);
        switch (match) {
            case PETS:
                return updatePet(uri, values, selection, selectionArgs);

            case PET_ID:
                selection = PetsContract.PetsEntry._ID + "=?";
                selectionArgs = new String[]{String.valueOf(ContentUris.parseId(uri))};
                return updatePet(uri, values, selection, selectionArgs);
            default:
                throw new IllegalArgumentException("Update is not possible for " + uri);

        }

    }

    private int updatePet(Uri uri, ContentValues values, String selection, String[] selectionArgs) {

        SQLiteDatabase database = mDbHelper.getWritableDatabase();
        int rowUpdated= database.update(PetsContract.PetsEntry.TABLE_NAME, values, selection, selectionArgs);
        if(rowUpdated!=0)
            getContext().getContentResolver().notifyChange(uri,null);

        return rowUpdated;

    }
}

PetContract.java-:

package com.example.android.pets.data;

import android.content.ContentResolver;
import android.net.Uri;
import android.provider.BaseColumns;

public final class PetsContract {
    private PetsContract(){}
    public static final String CONTENT_AUTHORITY = "com.example.android.pets";
    public static final Uri BASE_CONTENT_URI = Uri.parse("content://"+CONTENT_AUTHORITY);
    public static final String PATH_PETS = "pets";
    public static final Uri CONTENT_URI = Uri.withAppendedPath(BASE_CONTENT_URI,PATH_PETS);
    /*inner class that define the table content*/
    public static class PetsEntry implements BaseColumns {
        public static final String TABLE_NAME="pets"; //name of the database table.
        public static final String _ID=BaseColumns._ID;
        public static final String COLUMN_PET_NAME="name";
        public static final String COLUMN_PET_BREED="breed";
        public static final String COLUMN_PET_GENDER="gender";
        public static final String COLUMN_PET_WEIGHT="weight";
        /*possible value of the gender of the pet*/
        public static final int GENDER_UNKNOWN=0;
        public static final int GENDER_MALE=1;
        public static final int GENDER_FEMALE=2;
        public final static String CONTENT_LIST_TYPE= ContentResolver.CURSOR_DIR_BASE_TYPE+"/"+CONTENT_AUTHORITY+"/"+PATH_PETS;
        public final static String CONTENT_ITEM_TYPE = ContentResolver.CURSOR_ITEM_BASE_TYPE+"/"+CONTENT_AUTHORITY+"/"+PATH_PETS;

    }

}

[PetContract.txt](https://github.com/udacity/ud845-Pets/files/3237705/PetContract.txt)
[PetProvider.txt](https://github.com/udacity/ud845-Pets/files/3237707/PetProvider.txt)

**Comment by SudKul** [comment]
We have upgraded the code to AndroidX in this [commit](https://github.com/udacity/ud845-Pets/commit/942175e9bde6edcd7621d01ec7994b0f6161aeb9). 

We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
