### ISSUE TITLE
Fail to sync Gradle project

### ISSUE THREAD

**Issue by Akhil0609** [udacity/ud845-Pets#3]
Plz do help...

Error:Failed to open zip file.
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)
Re-download dependencies and sync project (requires network)

even after changing the  build.gradle

**Comment by ArunavaDW** [comment]
git clone https://github.com/udacity/ud845-Pets.git

Use this command inside your Android Projects directory.
after the command is executed 
open android studio, hit ctrl+o and choose the cloned project.
You will be good to go.

**Comment by vcctu85** [comment]
Closing this issue because student's question was answered.
