### ISSUE TITLE
Can't create the pets table

### ISSUE THREAD

**Issue by iver23** [udacity/ud845-Pets#34]
Hi, I have a strange issue, if I declare the statement of creating the pets table as a class variable (outside of the onCreate method), the database is created but the table is not created. However, if I declare the create table statement inside the onCreate method the database is created with the table.
I couldn't find a reasonable explanation for that!!
Any idea??

**Comment by PascalProgrammingX** [comment]
I declared the create statement in Contant Clas.
Create a Constant class, add the create table statement and the column names in it.
So you call that class every time you need it.
From: iver23
Sent: 12 August 2019 11:04 PM
To: udacity/ud845-Pets
Cc: Subscribed
Subject: [udacity/ud845-Pets] Can't create the pets table (#34)

Hi, I have a strange issue, if I declare the statement of creating the pets table as a class variable (outside of the onCreate method), the database is created but the table is not created. However, if I declare the create table statement inside the onCreate method the database is created with the table.
I couldn't find a reasonable explanation for that!!
Any idea??

**Comment by iver23** [comment]
It's strange, for me it doesn't work so I moved the declaration of create statement to onCreate method. thanks

**Comment by SudKul** [comment]
We have upgraded to code to AndroidX in this [commit](https://github.com/udacity/ud845-Pets/commit/942175e9bde6edcd7621d01ec7994b0f6161aeb9). 

We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
