### ISSUE TITLE
CatalogActivity 

### ISSUE THREAD

**Issue by GasolSun36** [udacity/ud845-Pets#35]
when i use this code line:`getLoaderManager().initLoader(PET_LOADER, null, this);`
the Android Studio shows the message like:

> "'Wrong 3rd argument type. Found: 'com.example.pets.CatalogActivity', required: 'android.app.LoaderManager.LoaderCallbacks<java.lang.Object>' less... 
> Inspection info:
> initLoader() in LoaderManager cannot be applied to:"

i don't know how to deal with it.
Can anyone help me please?thanks.

**Comment by GasolSun36** [comment]
ok，I know everybody. just use LoaderSupportManager method instead of LoadeeraManager method.

**Comment by PascalProgrammingX** [comment]
This method is Deprecated.
Will it  not affect  Newer  Android versions like Oreo and Pie?
#PascalProgramming

**Comment by tejoyv** [comment]
Yes facing the same issue 
Wrong 3rd argument type. Found 'com.example.carl.latestnews.MainActivity', required: 'android.app.LoaderManager.LoaderCallbacks<java.lang.Object>
Tried using LoaderSupportManager method but it shows depreciated

**Comment by nano-fruit** [comment]
Use
getSupportLoaderManager()

even though it's deprecated it worked for me.
Looking at gradle build files, properties, support libraries, migrating to AndroidX jetpack, invalidating cache and sycn project files didn't work. I wasted a lot of time, just because getSupportLoaderManager is showing depricated strike through sign in the ide. but it works. Good luck.

**Comment by amit-purohit** [comment]
> Use
> getSupportLoaderManager()
> 
> even though it's deprecated it worked for me.
> Looking at gradle build files, properties, support libraries, migrating to AndroidX jetpack, invalidating cache and sycn project files didn't work. I wasted a lot of time, just because getSupportLoaderManager is showing depricated strike through sign in the ide. but it works. Good luck.
thanks it worked

**Comment by amit-purohit** [comment]
thanks

**Comment by SudKul** [comment]
We have upgraded to code to AndroidX in this [commit](https://github.com/udacity/ud845-Pets/commit/942175e9bde6edcd7621d01ec7994b0f6161aeb9). 

We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
