### ISSUE TITLE
Issue in CatalogActivity while initializing the loader

### ISSUE THREAD

**Issue by tejoyv** [udacity/ud845-Pets#38]
when i use this code line:getLoaderManager().initLoader(PET_LOADER, null, this);
the Android Studio shows me the message like:

```
"'Wrong 3rd argument type. Found: 'com.example.pets.CatalogActivity', required: 'android.app.LoaderManager.LoaderCallbacks<java.lang.Object>' less...
Inspection info:
initLoader() in LoaderManager cannot be applied to:"
```

Tried getSupportLoader() method suggested in one of the threads on StackOverFlow but it shows depreciated.
I'm using the SdkVersion 28 for my app

Can anyone help me please? thanks.

**Comment by SudKul** [comment]
We have upgraded to code to AndroidX in this [commit](https://github.com/udacity/ud845-Pets/commit/942175e9bde6edcd7621d01ec7994b0f6161aeb9). 

We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
