### ISSUE TITLE
Getting this code working on first start

### ISSUE THREAD

**Issue by EngineerCharlie** [udacity/ud845-Pets#39]
SO, you've downloaded the code and got a million error messages. Yup, this is not being maintained, luckily I got your back I think. So, rather than just importing their project, it works better to start a new empty project and paste in the relevant stuff. So once you've started a new empty project with the wizard, go ahead and copy the "main" folder from 
"...AndroidStudioProjects\ud845-Pets-starting-point\app\src" 
to your new folder (mine is "AndroidStudioProjects\pets\app\src").

Ok, good start but it still probably won't run. First, lets do the java files. In catalog activity, add this to the imports:
`import com.google.android.material.floatingactionbutton.FloatingActionButton;`
and remove the unused code (AS should highlight it).

In the editor activity add these to the imports:
```
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.NavUtils;
```
And again remove the unused code.

Next we'll do the gradle file, open up build.gradle (:app) and add this implementation down at the bottom:
`implementation "com.google.android.material:material:1.1.0"`

Finally, in activity_catalogue.xml you will need need to change the 
`<android.support.design.widget.FloatingActionButton`
to:
`<com.google.android.material.floatingactionbutton.FloatingActionButton`

Ok, now it should work. If not, it should be almost there. Post any additional steps below.

**Comment by ronanrush** [comment]
Thanks, this helped greatly

**Comment by nicholeb** [comment]
Thanks - this worked for me except that I also had to add import androidx.appcompat.app.AppCompatActivity; to CatalogActivity.java

**Comment by ZCoder9** [comment]
Thank you so much.

**Comment by SudKul** [comment]
Thanks, @ChazFromEarth 
We have upgraded to code to AndroidX in this [commit](https://github.com/udacity/ud845-Pets/commit/942175e9bde6edcd7621d01ec7994b0f6161aeb9).
