### ISSUE TITLE
Deprecated import classes in Lesson 4-10 causing errors

### ISSUE THREAD

**Issue by EngineerCharlie** [udacity/ud845-Pets#40]
So after alot of hair pulling I found a problem related to the import classes used in this lesson. An error is thrown from getLoaderManager().initLoader(... , this). I'm not sure what the actual solution is going forward, but for the moment using the deprecated import classes shown below fixes the error.

So change these (android suggested) import classes:

import androidx.loader.app.LoaderManager;
import androidx.loader.content.CursorLoader;
import androidx.loader.content.Loader;

To these deprecated import classes:

import android.app.LoaderManager;
import android.content.CursorLoader;
import android.content.Loader;

**Comment by SudKul** [comment]
We have upgraded to code to AndroidX in this [commit](https://github.com/udacity/ud845-Pets/commit/942175e9bde6edcd7621d01ec7994b0f6161aeb9). 

We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
