### ISSUE TITLE
E/SQLiteDatabase: Error inserting data

### ISSUE THREAD

**Issue by chekwon78** [udacity/ud845-Pets#7]
The code, as is, runs fine on my emulator. However, when I click 'Insert Dummy Data' it fails to insert the data in the database. The following is the error I get on my logcat:

3-23 16:32:25.059 5771-5771/com.example.android.pets E/SQLiteDatabase: Error inserting name=Toto gender=1 weight=7 breed=Terrier
                                                                        android.database.sqlite.SQLiteException: table pets has no column named gender (code 1): , while compiling: INSERT INTO pets(name,gender,weight,breed) VALUES (?,?,?,?)

Any help would be greatly appreciated

**Comment by AlShaymaa1** [comment]
uninstall the app and install it again

**Comment by Bniky** [comment]
This happen to me and I didn't space out the data types in dbhelper class example. " TEXT NOT NULL, "

**Comment by himanshuchokker1** [comment]
i uninstalled my app and re installed it but the problem remains same 
column has no table error while compiling INSERT INTO ....

**Comment by vincentyahaha** [comment]
Had the same issue, here is my solution. 
Clear the cache, and run the app again.
