### ISSUE TITLE
Failed to sync Gradle project 'ud845-Pets-starting-point'

### ISSUE THREAD

**Issue by Mohamad-Hasan** [udacity/ud845-Pets#8]
I downloaded the zip file, extracted it, imported the project in android studio, but I got this message : 

Error:Cause: failed to find target with hash string 'android-24' in: C:\Users\WinDows7\AppData\Local\Android\Sdk
Possible cause: Build properties not found for package Android SDK Platform 24, rev 3
<a href="install.android.platform">Install missing platform(s) and sync project</a>

please help ,

Thanks

**Comment by Mohamad-Hasan** [comment]
and I clicked on the ( Install missing platform(s) and sync project ) link but it didn't work

**Comment by viral999g** [comment]
Update components in Audio studio...it is outdated!

**Comment by vcctu85** [comment]
Hi @Mohamad-Hasan , try downloading SDK for API 24 from the Android SDK Manager. Please let me know if that works.

**Comment by vcctu85** [comment]
Closing this issue because student's question was answered.

**Comment by AhmedGsm** [comment]
Hi, I created a new branch gradle-update, its main function is to update all gradle files inluding dependencies, maven repositories, etc , so if the user merge the main branch to my gradle-update branch he will earn a full update of gradle files , and not need to perform any update and gradles fixes, he just pull my gradle-update branch then perform merge from the main working branch and earn all update,
I just implement a pull request if the udacity user accept my request.
